name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: real-voice-limiter # -${{ matrix.goos-goarch}}
    steps:
      - uses: actions/checkout@v4

      - name: get golang version
        id: golang-version
        run: |
          echo golang_version=$(cat .tool-versions | grep golang | cut -d' ' -f2) >> $GITHUB_OUTPUT

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: ${{ steps.golang-version.outputs.golang_version }}
          targets: linux/amd64,linux/arm64,windows/amd64,darwin/amd64,darwin/arm64
          dest: build
          ldflags: -s -w
          v: true

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/*
          if-no-files-found: warn
